### ISSUE TITLE
Implement option to compile main quality metrics

### ISSUE THREAD

**Issue by jeremie-fouquet** [milaurose/fMRI_phantom_analysis#7]
I'd like to implement an option to automatically output and compile the main quality metrics to facilitate comparison between QC sessions.

My first thought would be to simply append a new line to a .csv file, which would accumulate the metrics from different QC sessions. One could then easily plot trends over time and compute statistics to detect outliers (this could also be automated). 

@gdevenyi and @milaurose, do you have better ideas for the format to which to export the metrics? 

Thank you.

**Comment by gdevenyi** [comment]
CSV and JSON are good choices for something reasonably parsable for outputs.

I  think the part that aggregates should probably be done separate from this code, so this code does "one thing". If anything, we just add clean output that can be parsed and aggregated by something else.

**Comment by jeremie-fouquet** [comment]
Ok. Yes, I understand the idea for this code to do "one thing". I'd then just add an option for a clean output of the quality metrics, most likely into a CSV file.

For aggregating and analyzing the results from different QC sessions, it will be a pretty simple piece of code. Not sure where I'll store it just now, but that could be another discussion.

**Comment by milaurose** [comment]
I do like Jeremie's idea of tracking longitudinal changes, as this feature is included in the proprietary clinical software as well. I would like to add it.
